### ISSUE TITLE
Need HTTPS on ORM app link from GitHub Org

### ISSUE THREAD

**Issue by jbampton** [OnlineRacingManager/orm-project-management#1]
![Screen Shot 2021-01-26 at 3 26 28 pm](https://user-images.githubusercontent.com/418747/105804276-1ccbbe80-5feb-11eb-960c-eb33ca96ec69.png)

**Comment by TJSteel** [comment]
I've updated the links to the app on github,

This is a non issue though, the root domain is not used as this is a multi tenant app, and there is an ssl certificate setup for the subdomains *(*.onlineracingmanager.com)

The link in the screenshot above has a redirect to the original subdomain, and the backend forces https use too, so you can't actually browse ORM using http
